name: Build

on:
  push:
    branches: [master]

env:
  NAME: ghcr.io/viva-la-vita/gateway

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: viva-la-vita
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ env.NAME }}
          build-args: CLOUDFLARE_TOKEN=${{ secrets.CLOUDFLARE_TOKEN }}
          cache-from: type=registry,ref=${{ env.NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.NAME }}:buildcache,mode=max
